[package]
name = "thaqqa_server"
version = "0.1.0"
edition = "2021"

[dependencies]
may_minihttp = "0.1"
regex = "1.10.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
svg = "0.17.0"
base64 = "0.22.1"